### ISSUE TITLE
Is this tool working? Can I use it for Kinect One (v2) projector calibration? 

### ISSUE THREAD

**Issue by mambro** [SENSlab/ProCamCalibration#1]
Hi, I am an italian research scholar. I'm working on Projective Augmented Reality with a robotic head. Unfortunately, I still have problems with Camera (I'm using a Kinect One) - Projector calibration.

I have: 
1) Realized with my supervisor a new ProCam Calibration tool based on Matlab ProCamCalib toolbox (https://code.google.com/archive/p/procamcalib/) with automatic splitting and recognition of projected and physical chessboards, but this gives us not perfect results (residual reprojection error about 1... px)

2) Conveniently modified the promising 3D Scanning Software (http://mesh.brown.edu/calibration/) to make it able to work with Kinect One but there is something to change that avoids to manage good results.

Therefore, I'd like to know if your pro_cam_calib tool here shared works properly and I can use it to solve my problems calibrating a Kinect One (v2) with a fixed-focus Optoma pocket projector.

Thank you in advance,

Michele Mambrini

**Comment by asama-yaya** [comment]
In general, pro-cam system calibration is more difficult and error is big than camera calibration. Because focus blur is big problem in procam calibration. So, if your assumed space is big and you use Kinect sensor, I recommend you to use RoomAlive in MicroSoft (But, this use Kinect v2).
https://github.com/Kinect/RoomAliveToolkit

As my answer of your question, residual reprojection error in my calib tool is less than 1 px, when I used LCD projector (1280x800) and PointGrey camera (1280x960). So, I think that you can solve your problem with my tool. But, my method seems to be similar to Matlab ProCamCalib toolbox. The cause may be your technical problem while calibration.

However, as I said in first, procam calibration error is generally big. So, I think that you can ignored about 1 px reprojection error.

**Comment by mambro** [comment]
Thank you very much for your answer. I'd like to try your promising toolbox.  Can you rapidly translate in english the  説明書てきな.pdf  where you show a sort of  manual of your tool, please?  I've tried with google translate, but the automatic translation is not good enough.
